### ISSUE TITLE
Werid Terminal Issue

### ISSUE THREAD

**Issue by lees3** [kittens-mittens/team-app#82]
There is this issue in my terminal that says it can't associate the buttons pattern listed in the banner/buttons.html config file. There isn't a buttons.html file in the banner folder or in the config file. I'm not sure how to resolve this issue. Thank you

@thomasjbradley

<img width="1366" alt="Screen Shot 2020-02-19 at 1 11 18 AM" src="https://user-images.githubusercontent.com/31832013/74806940-4184c580-52b5-11ea-9362-cc07a6332bea.png">

**Comment by JasmineCT** [comment]
I found the issue its in your banner config, you wrote buttons not banner. 
@lees3 you will have to go in and fix that
<img width="728" alt="Screen Shot 2020-02-19 at 11 41 15 AM" src="https://user-images.githubusercontent.com/31959259/74854043-c222e080-530c-11ea-9681-cf7ffc07f92e.png">
